### PR TITLE
Complete 108 r4

### PR DESCRIPTION
**Pull request by rob-reynolds**

### CODE REVIEW

**Comment by rob-reynolds** [comment]
Hello Yanyan.

Please merge this commit to move 108 to complete.

**Comment by yanyanhu2** [comment]
it is good and ready to go.

**Comment by rob-reynolds** [comment]
Hey Yanyan.  Could you please click the "review" button and Approve it?

Github shows reviews pending.

**Comment by rob-reynolds** [comment]
This moves the CQL file from the "in progress" folder to the "completed" folder.

**Pull request merged**
